baseurl = "https://erickcamacho.com"
languageCode = "en"
title = "Erick Camacho"
theme = "kiss_custom"
copyright = "&copy; <a href=\"https://github.com/ecamacho\">Erick Camacho</a> 2022"
disqusShortname = "shortname"
googleAnalytics = "G-49FWBT8ZWW"
# Number of posts per page
Paginate = 5
enableRobotsTXT = true


[params.assets]
customCSS = ["css/custom.css"]

[params.rss]

includeContent = true # Includes whole content in rss
authorName = "Erick Camacho" # Site author's full name

[params.info]
adsense = "" # Adsense ID (ID only, without ca-pub-)
enableSocial = false # Adds OpenGraph and Twitter cards
homeTitle = "" # Title for home page
poweredby = true # Adds powered by Hugo and Kiss below Copyright section
related = false # Includes related articles

[params.opengraph.facebook]
admins = [] # array of Facebook IDs
appID = ""
pageID = ""

[params.opengraph.twitter]
page = "" # Twitter Page username. If not set, params.social.twitter will be used.

[params.social]

twitter = "ecamacho"
github = "ecamacho"
email = "me@erickcamacho.com"
linkedin = ""
gitlab = ""
instagram = ""
codepen = ""
facebook = ""

[params.social.config]
platforms = ["twitter","github"]

[taxonomies]
tag ="tags"

[blackfriday]
hrefTargetBlank = true

