baseurl = "https://www.example.com"
languageCode = "en"
title = "Erick Camacho"
theme = "kiss"
copyright = "&copy; <a href=\"https://github.com/ecamacho\">Erick Camacho</a> 2018"
disqusShortname = "shortname"
googleAnalytics = ""
# Number of posts per page
Paginate = 5
enableRobotsTXT = true


[params.assets]
customCSS = ["css/custom.css"]

[params.rss]

includeContent = true # Includes whole content in rss
authorName = "Emir Ribic" # Site author's full name
authorEmail = "ribice@gmail.com"

[params.info]
adsense = "" # Adsense ID (ID only, without ca-pub-)
enableSocial = false # Adds OpenGraph and Twitter cards
homeTitle = "" # Title for home page
poweredby = true # Adds powered by Hugo and Kiss below Copyright section
related = true # Includes related articles

[params.opengraph.facebook]
admins = [] # array of Facebook IDs
appID = ""
pageID = ""

[params.opengraph.twitter]
page = "" # Twitter Page username. If not set, params.social.twitter will be used.

[params.social]

twitter = "ecamacho"
github = "ecamacho"
email = ""
linkedin = ""
gitlab = ""
instagram = ""
codepen = ""
facebook = ""

[params.social.config]
platforms = ["twitter","github"]

[params.matomoAnalytics]
siteID = 1
rootURL = "//matomo.example.com/"

[params.fathomAnalytics]
rootURL = "//fathom.example.com/"

[taxonomies]
tag ="tags"

[blackfriday]
hrefTargetBlank = true

